### ISSUE TITLE
iOS release

### ISSUE THREAD

**Issue by MarcoSpeziali** [stonega/tsacdop#32]
I read that the API you used is not free, so you did not include it in the repository. I could build the app for iOS, but I'd still be missing the API key. It is possible to have an unsigned ipa that I can manually sign and install?

**Comment by stonega** [comment]
I would like to help you, but  I don't understand about unsigned ipa you meant, can you tell me more? 
Also two search engines are supported right now, podcast index is free to all, you can register and get the api key in https://api.podcastindex.org/developer_home

**Comment by MarcoSpeziali** [comment]
I'll try to build the app using podcastindex and I'll get in touch

**Comment by MarcoSpeziali** [comment]
Have you ever built for iOS? Does the app run as intended?
After some compilation errors: `AppDelegate.swift:20, from FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")) to FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)` the app compiles and can be installed on a device. Unfortunately there seems to be some runtime errors:

```
2020-11-27 10:35:36.551944+0100 Runner[564:40659] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      Workmanager.initialize (package:workmanager/src/workmanager.dart:100:30)
#3      SettingState.setWorkManager (package:tsacdop/state/setting_state.dart:187:17)
#4      SettingState.addListener.<anonymous closure> (package:tsacdop/state/setting_state.dart:121:9)
#5      SettingState.addListener.<anonymous closure> (package:tsacdop/state/setting_state.dart:119:31)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#14     SettingState._getUpdateInterval (package:tsacdop/state/setting_state.dart)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#23     KeyValueStorage.getInt (package:tsacdop/local_storage/key_value_storage.dart)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#32     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
#33     _rootRunUnary (dart:async/zone.dart:1198:47)
#34     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#39     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#40     _rootRun (dart:async/zone.dart:1190:13)
#41     _CustomZone.run (dart:async/zone.dart:1093:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
2020-11-27 10:35:36.552564+0100 Runner[564:40659] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method registerPeriodicTask on channel be.tramckrijte.workmanager/foreground_channel_work_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      Workmanager.registerPeriodicTask (package:workmanager/src/workmanager.dart:158:32)
#3      SettingState.setWorkManager (package:tsacdop/state/setting_state.dart:191:17)
#4      SettingState.addListener.<anonymous closure> (package:tsacdop/state/setting_state.dart:121:9)
#5      SettingState.addListener.<anonymous closure> (package:tsacdop/state/setting_state.dart:119:31)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#14     SettingState._getUpdateInterval (package:tsacdop/state/setting_state.dart)
#15     _rootRunUnary (dart:async/zone.dart:1198:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#23     KeyValueStorage.getInt (package:tsacdop/local_storage/key_value_storage.dart)
#24     _rootRunUnary (dart:async/zone.dart:1198:47)
#25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#32     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
#33     _rootRunUnary (dart:async/zone.dart:1198:47)
#34     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#39     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#40     _rootRun (dart:async/zone.dart:1190:13)
#41     _CustomZone.run (dart:async/zone.dart:1093:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
2020-11-27 10:36:15.615328+0100 Runner[564:40659] flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2020-11-27 10:36:15.615438+0100 Runner[564:40659] flutter: The following assertion was thrown while finalizing the widget tree:
2020-11-27 10:36:15.615466+0100 Runner[564:40659] flutter: Duplicate GlobalKey detected in widget tree.
2020-11-27 10:36:15.615542+0100 Runner[564:40659] flutter: The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of
2020-11-27 10:36:15.615576+0100 Runner[564:40659] flutter: the widget tree being truncated unexpectedly, because the second time a key is seen, the previous
2020-11-27 10:36:15.615597+0100 Runner[564:40659] flutter: instance is moved to the new location. The key was:
2020-11-27 10:36:15.615615+0100 Runner[564:40659] flutter: - [LabeledGlobalKey<DiscoveryPageState>#93ae1]
2020-11-27 10:36:15.615633+0100 Runner[564:40659] flutter: This was determined by noticing that after the widget with the above global key was moved out of its
2020-11-27 10:36:15.615770+0100 Runner[564:40659] flutter: previous parent, that previous parent never updated during this frame, meaning that it either did
2020-11-27 10:36:15.615837+0100 Runner[564:40659] flutter: not update at all or updated before the widget was moved, in either case implying that it still
2020-11-27 10:36:15.616095+0100 Runner[564:40659] flutter: thinks that it should have a child with that global key.
2020-11-27 10:36:15.616266+0100 Runner[564:40659] flutter: The specific parent that did not update after having one or more children forcibly removed due to
2020-11-27 10:36:15.616441+0100 Runner[564:40659] flutter: GlobalKey reparenting is:
2020-11-27 10:36:15.616544+0100 Runner[564:40659] flutter: - KeyedSubtree-[<_SearchBody.suggestions>]
2020-11-27 10:36:15.616634+0100 Runner[564:40659] flutter: A GlobalKey can only be specified on one widget at a time in the widget tree.
2020-11-27 10:36:15.616763+0100 Runner[564:40659] flutter:
2020-11-27 10:36:15.616866+0100 Runner[564:40659] flutter: When the exception was thrown, this was the stack:
2020-11-27 10:36:15.616944+0100 Runner[564:40659] flutter: #0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2881:15)
2020-11-27 10:36:15.617093+0100 Runner[564:40659] flutter: #1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2906:8)
2020-11-27 10:36:15.617240+0100 Runner[564:40659] flutter: #2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:915:18)
2020-11-27 10:36:15.617355+0100 Runner[564:40659] flutter: #3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
2020-11-27 10:36:15.617462+0100 Runner[564:40659] flutter: #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
2020-11-27 10:36:15.617529+0100 Runner[564:40659] flutter: #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
2020-11-27 10:36:15.617651+0100 Runner[564:40659] flutter: #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
2020-11-27 10:36:15.617776+0100 Runner[564:40659] flutter: #10     _invoke (dart:ui/hooks.dart:251:10)
2020-11-27 10:36:15.617892+0100 Runner[564:40659] flutter: #11     _drawFrame (dart:ui/hooks.dart:209:3)
2020-11-27 10:36:15.618010+0100 Runner[564:40659] flutter: (elided 3 frames from dart:async)
2020-11-27 10:36:15.618117+0100 Runner[564:40659] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2020-11-27 10:39:24.305231+0100 Runner[564:40659] flutter: Another exception was thrown: Duplicate GlobalKey detected in widget tree.
```

This happens when I search for a podcast from the Categories section. The manual search works just fine.
I also found some problems during playback. The app is constantly in the "buffering" state even though the podcasts starts playing. This does not enable the pause button. (screen 1)
Also on iPhone's with the notch the safe area is not always respected (Screen 2)

![Screen 1](https://user-images.githubusercontent.com/1831539/100435164-d6ff8200-309d-11eb-8e3e-de955bdf216d.PNG)

![Screen 2](https://user-images.githubusercontent.com/1831539/100435240-f696aa80-309d-11eb-9360-e0d52078e7d1.PNG)

**Comment by stonega** [comment]
I tried to build iOS version months ago on my old macbook, run successfully but had some issues too. 
You might need to configure for some plugins, looks like the error is about Flutter Downloader plugin. 
I do have plan to publish iOS version in the future, but I focus on new features right now.
